"""
AI Trace Service

Persists prompts and AI responses for debugging.
"""

from pathlib import Path


class AITraceService:
    """
    Handles saving prompts and responses generated by AI providers.
    """

    def __init__(
        self,
        workspace: Path,
    ) -> None:
        self.workspace = workspace

        self.prompts_dir = workspace / "prompts"
        self.responses_dir = workspace / "responses"
        self.validated_dir = workspace / "validated"

        self.prompts_dir.mkdir(parents=True, exist_ok=True)
        self.responses_dir.mkdir(parents=True, exist_ok=True)
        self.validated_dir.mkdir(parents=True, exist_ok=True)

    def save_prompt(
        self,
        name: str,
        prompt: str,
    ) -> None:
        """
        Save a prompt.
        """

        (self.prompts_dir / f"{name}.txt").write_text(
            prompt,
            encoding="utf-8",
        )

    def save_response(
        self,
        name: str,
        response: str,
    ) -> None:
        """
        Save the raw provider response.
        """

        (self.responses_dir / f"{name}.json").write_text(
            response,
            encoding="utf-8",
        )

    def save_validated(
        self,
        name: str,
        content: str,
    ) -> None:
        """
        Save validated JSON.
        """

        (self.validated_dir / f"{name}.json").write_text(
            content,
            encoding="utf-8",
        )
